#!/bin/bash
# Title: sb-adblock-hosts
# Author: simonizor
# License: MIT
# Dependencies: curl
# Description: A script that downloads Steven Black's hosts file (github.com/StevenBlack/hosts) configured for adblock and keeps it up to date

# function to get ETag and Content-Length from header response
gethostsheaders() {
    export HOSTS_VERSION="$(curl -sL "https://raw.githubusercontent.com/StevenBlack/hosts/master/package.json" | grep '"version":' | cut -f4 -d'"')"
    if [[ -z "$HOSTS_VERSION" ]]; then
        echo "Error getting current hosts file version.  Are we connected to the internet?"
        exit 0
    fi
    export HOSTS_LENGTH="$(curl -sLIX HEAD "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" | grep -m1 'Content-Length:' | cut -f2 -d' ' | tr -d '\r' | tr -d '$')"
    if [[ -z "$HOSTS_LENGTH" ]]; then
        echo "Error getting content length of current hosts file.  Are we connected to the internet?"
        exit 0
    fi
}
# function to download hosts file
downloadhosts() {
    curl -sL "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" -o /tmp/sb-adblock-hosts.tmp || true
    HOSTS_DL_LENGTH="$(cat /tmp/sb-adblock-hosts.tmp | wc -c)"
    if [[ "$HOSTS_LENGTH" != "$HOSTS_DL_LENGTH" ]]; then
        echo "Error downloading hosts file from 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'"
        echo "Content length of original $HOSTS_LENGTH does not match content length of download $HOSTS_DL_LENGTH"
        rm -f /tmp/sb-adblock-hosts.tmp
        exit 1
    fi
    if [[ ! -f "/etc/hosts.orig.bak" ]]; then
        cp /etc/hosts /etc/hosts.orig.bak
    else
        cp /etc/hosts /etc/hosts.last.bak
    fi
    mv /tmp/sb-adblock-hosts.tmp /etc/hosts
    echo "CURRENT_VERSION=\"$HOSTS_VERSION\"" > /etc/sb-adblock-hosts.conf
    echo "Updated hosts file to version $HOSTS_VERSION"
}
# check if running as root
if [[ "$EUID" != "0" ]]; then
    echo "sb-adblock-hosts must be ran as root; exiting..."
    exit 0
fi
# check if /etc/sb-adblock-hosts.conf exists
if [[ ! -f "/etc/sb-adblock-hosts.conf" ]]; then
    gethostsheaders
    downloadhosts
else
    source /etc/sb-adblock-hosts.conf
    gethostsheaders
    if [[ "$CURRENT_VERSION" != "$HOSTS_VERSION" ]]; then
        downloadhosts
    fi
fi
